### ISSUE TITLE
SyntaxError: Unexpected reserved word​​ -- Sublime Text 3 + Wallaby + Wallabify

### ISSUE THREAD

**Issue by thomasconner** [wallabyjs/wallabify#6]
When I try to run my wallaby configuration I am seeing

```
[Info]: wallaby.js started​​​​​
​​[Error]: Failed to load configuration file:  /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/Core/SDK/node_modules/wallabify/index.js:31​​
​​[Error]: class Wallabify {​​
​​[Error]: ^^^^^​​
​​[Error]: SyntaxError: Unexpected reserved word​​
​​[Error]:   at exports.runInThisContext (vm.js:73:16)​​
​​[Error]:   at Module.n._compile (/Users/Thomas/Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:15:8002)​​
​​[Error]:   at Module.s.require (/Users/Thomas/Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:18:20801)​​
​​[Error]:   at Object.<anonymous> (/Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/Core/SDK/wallaby.js:2:17)​​
```

I can't seem to figure out why this is the case and I don't see anything else referencing this problem. Any ideas?

Here is my wallaby config

```
/* eslint-disable */
var wallabify = require('wallabify');

module.exports = function(wallaby) {
  var compiler = wallaby.compilers.babel({
    babelrc: true,
    sourceMaps: 'inline'
  });
  var postprocessor = wallabify({
    debug: true,
    entryPatterns: [
      'test/specs/**/*.js'
    ]
  });

  return {
    debug: true,
    files: [
      { pattern: 'package.json', load: false },
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'test/helpers.js', load: false },
      { pattern: 'test/specs/**/*.js', ignore: true }
    ],
    tests: [
      { pattern: 'test/specs/**/*.js', load: false }
    ],
    testFramework: 'mocha',
    compilers: {
      '**/*.js': compiler
    },
    postprocessor: postprocessor,
    env: {
      runner: require('phantomjs2-ext').path,
      params: { runner: '--web-security=false' }
    },
    bootrstrap: function() {
      window._moduleBundler.loadTests();
    }
  };
};
```

**Comment by thomasconner** [comment]
I figured out a solution. Just put 

```
require('babel-register')({
  ignore: /\/node_modules\/(?!wallabify\/)/
});
```

at the top of your wallaby config file.

**Comment by ArtemGovorov** [comment]
Thanks for the update!

Another option is to install a newer node.js version (that supports ES6). You may install the newer version side by side with your existing one with [nvm](https://github.com/creationix/nvm) if you like, and [configure node.js path](http://wallabyjs.com/docs/intro/install.html#nodejs-2) in `.sublime-settings` for your wallaby package.
